language:         python
cache:            pip
python:
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev

install:
  - pip install codecov
  - pip install -r requirements.txt
  - python setup.py install
script:
  - coverage run tests/test_lan_explorer.py

after_success:
  - codecov
